parameters:
  # Can be refactored later and written as Entities and ability to manage this list from admin panel
  lottery_min_money: 1
  lottery_max_money: 100
  lottery_min_loyalty: 10
  lottery_max_loyalty: 1000
  lottery_loyalty_coef: 0.1
  lottery_physical_gifts:
    - T-Shirt
    - Cup
    - Candle
    - MacBook